#model quizlet https://quizlet.com/5268792/apush-review-flash-cards/
def format(name, i):
  s=f'''
        <mxCell id="ooiS89k2z1iW1_5buQfN-{i}" value="{name}" style="rounded=0;whiteSpace=wrap;html=1;" vertex="1" parent="1">
          <mxGeometry x="365" y="240" width="120" height="60" as="geometry" />
        </mxCell>
    '''
  return s

terms = [
        "Great Columbian / Biological Exchange",
        "Christopher Columbus",
        "Bartolomeo de las Casas",
        "Spanish empire",
        "French empire",
        "English/British Empire",
        "Jamestown",
        "Mayflower Compact",
        "Chesapeake colonies",
        "Virginia colony",
        "1619",
        "Bacon's rebellion",
        "Maryland colony",
        "Toleration Act",
        "New England colonies",
        "Massachusetts Bay Colony",
        "John Winthrop",
        "City upon a hill",
        "Anne Hutchinson",
        "King Philip's war",
        "Salem Witch Trials",
        "Rhode Island Colony",
        "Disestablishment",
        "Connecticut colony",
        "Fundamental Orders",
        "New Amsterdam",
        "Restoration colonies",
        "New York colony",
        "Pennsylvania colony",
        "William Penn",
        "Georgia colony",
        "James Oglethorpe",
        "Mercantilism",
        "Triangular trade",
        "Navigation Acts",
        "salutary/benign neglect",
        "Dominion of New England",
        "Glorious Revolution (in America)",
        "Puritanism",
        "Enlightenment",
        "John Locke",
        "Benjamin Franklin",
        "First Great Awakening",
        "Jonathan Edwards",
        "George Whitefield",
        "18th century immigration",
        "American Slavery",
        "Stono Rebellion",
        "Zenger case",
        "French and Indian/Seven Year's War",
        "Albany Plan of Union",
        "Benjamin Franklin Achievements",
        "Pontiac's Rebellion",
        "Proclamation of 1763",
        "Stamp Act",
        "Sons of Liberty",
        "Daughters of Liberty",
        "Declaratory Act",
        "Townshend Acts",
        "Boston Massacre",
        "Boston Tea Party",
        "Coercive/Intolerable Acts",
        "American Revolution (1775-1783)",
        "Continental Congress",
        "Common sense",
        "Declaration of Independence",
        "General George Washington",
        "Battle of Saratoga",
        "French Alliance",
        "Loyalists",
        "Articles of Confederation",
        "Newburgh Conspiracy",
        "Peace of Paris (1783)",
        "Republicanism",
        "Virginia Statute of Religious Freedom",
        "Republican Motherhood",
        "Land ordinance and Northwest Ordinance",
        "Shay's Rebellion",
        "Philadelphia (Constitutional) Convention",
        "James Madison",
        "Virginia Plan",
        "New Jersey Plan",
        "Great Compromise",
        "3/5 Compromise",
        "Charles Beard's Constitution thesis",
        "Ratification of the Constitution debate",
        "Federalist Papers",
        "Bill of Rights",
        "Washington's Presidency (1789-1797)",
        "Hamilton's financial program",
        "Establishment of Washington D.C as nation's capital",
        "Neutrality Proclamation",
        "Jay's Treaty",
        "Pinckney's Treaty",
        "Whiskey Rebellion",
        "First Party System: Federalists vs. Democratic-Republicans",
        "Washington's Farewell Address",
        "John Adams' Presidency (1797-1801)",
        "XYZ Affair",
        "Quasi-War",
        "Alien and Sedition Acts",
        "Virginia and Kentucky Resolutions",
        "Election of 1800",
        "Midnight appointments",
        "Jefferson's Presidency (1801-1809)",
        "Second Great Awakening",
        "Charles Finney",
        "Louisiana Purchase",
        "Lewis and Clark Expedition",
        "Burr Conspiracy",
        "Impressment",
        "Chesapeake-Leopard incident",
        "Embargo Act",
        "Tenskwatawa/The Prophet",
        "Tecumseh and the Indian Confederation",
        "James Madison's Presidency (1809-1817)",
        "War Hawks",
        "War of 1812 (1812-1815)",
        "Hartford Convention",
        "Treaty of Ghent",
        "Battle of New Orleans",
        "James Monroe (1817-1825)",
        "Era of Good Feelings",
        "Adams-Onis/Transcontinental Treaty",
        "Monroe Doctrine",
        "U.S Industrial Revolution",
        "Eli Whitney",
        "Samuel Slater",
        "Tariff of 1816",
        "Second Bank of the U.S",
        "National road",
        "Robert Fulton",
        "Erie Canal",
        "De Witt Clinton",
        "Bonus Bill",
        "Lowell-Waltham system",
        "Separate Spheres",
        "John Marshall's Supreme Court",
        "Marbury vs. Madison",
        "Gibbons decision",
        "Dartmouth College decision",
        "McCulloch decision",
        "Worcester Decision",
        "Antebellum urbanization",
        "Squatters and preemption",
        "Panic of 1819",
        "Sectionalism",
        "Missouri Crisis and Compromise",
        "Democracy in America",
        "Universal Manhood Suffrage",
        "Dorr Rebellion",
        "Spoil's system",
        "National Party Conventions",
        "Maysville Road veto",
        "Daniel Webster",
        "Liberty and Union Speech",
        "John C. Calhoun",
        "Tariff of Abominations",
        "South Carolina Exposition and Protest",
        "Nullification Crisis",
        "Force Bill (1833)",
        "Compromise Tariff of 1833",
        "Eastern Indian Removal",
        "Trail of Tears (1838)",
        "Bank War",
        "Taney Court",
        "Charles River Bridge Case",
        "Second Party System: Democrats and Whigs",
        "Presidency of Martin Van Buren (1837-1841)",
        "Panic of 1837 and economic depression",
        "Independent Treasury",
        "Election of 1840",
        "Noah Webster",
        "James Fenimore Cooper",
        "Walt Whitman",
        "Herman Melville",
        "Nathaniel Hawthorne",
        "Hudson Valley School of Art",
        "Oneida",
        "Shakers",
        "Mormons",
        "Transcendentalists",
        "Ralph Waldo Emerson",
        "Henry David Thoreau",
        "Feminism-Woman's Rights",
        "Oberlin and Mount Holyoke colleges",
        "Lucretia Mott",
        "Elizabeth Cady Stanton",
        "Susan B. Anthony",
        "Seneca Falls Convention",
        "Catherine Beecher",
        "Horace Mann",
        "Maine Laws",
        "Dorothea Dix",
        "Penitentiaries",
        "American Colonization Society",
        "Abolitionism",
        "William Lloyd Garrison",
        "The Liberator",
        "Frederick Douglass",
        "Wendell Phillips",
        "David Walker",
        "Harriet Tubman and the Underground Railroad",
        "King Cotton",
        "Upper South",
        "Deep South",
        "Planter Class",
        "Toussaint L'Ouverture's rebellion in Haiti (1804)",
        "Denmark Vesey rebellion (1822)",
        "Nat Turner rebellion (1831)",
        "Manifest Destiny",
        "Great American Desert",
        "Mountain Men'",
        "Texas Revolution (1836)",
        "Overland Trails",
        "Mormon Migration to Utah",
        "Brigham Young",
        "Oregon Country",
        "John C. Fremont",
        "James K. Polk's Presidency (1845-1849)",
        "Mexican War (1846-1848)",
        "Wilmot Provisio (1846)",
        "Treaty of Guadalupe-Hidalgo (1848)",
        "California Gold Rush",
        "Compromise of 1850",
        "Cyrus McCormick reaper",
        "John Deere steel plow",
        "Antebellum mass immigration (1840's and 50's)",
        "Know-Nothings and the American Party",
        "Uncle Tom's Cabin (1853)",
        "Fugitive Slave Act",
        "Anthony Burns incident",
        "Young America movement",
        "Gadsden Purchase",
        "Kansas-Nebraska Act (1854)",
        "Stephen Douglas",
        "Free-soil ideology",
        "Republican Party",
        "Bleeding Kansas",
        "Sack of Lawrence",
        "Pottawatomie Massacre",
        "Beating of Charles Sumner",
        "Dred Scott decision (1857)",
        "Lecompton Crisis (1857-1858)",
        "Lincoln Douglas debates",
        "John Brown's raid at Harper's Ferry",
        "Election of 1860",
        "Secession Crisis",
        "Confederate States of America",
        "Abraham Lincoln's presidency (1861-1865)",
        "Civil War (1861-1865)",
        "Union military draft",
        "New York City draft riot",
        "Lincoln's restriction of civil liberties",
        "Copperheads / Peace Democrats",
        "Republican (Civil War) economic legislation",
        "Union financing of war",
        "Confederate constitution",
        "Confederate military draft",
        "Confederate financing of war",
        "Trent affair",
        "Battle of Gettysburg and Siege of Vicksburg",
        "Election of 1864",
        "William T. Sherman and the March to the Sea",
        "Total war",
        "Confiscation Acts",
        "Emancipation Proclamation",
        "13th Amendment (1865)",
        "Civil War's effects on women",
        "Clara Barton",
        "Reconstruction (1863-1877)",
        "Freedman's Bureau",
        "Presidential Reconstruction plans (Lincoln and Johnson)",
        "Black codes",
        "Election of 1866",
        "Congressional (Radical) Reconstruction plans",
        "14th Amendment",
        "15th Amendment",
        "Lucy Stone vs. Susan B. Anthony and Elizabeth Cady Stanton",
        "Congressional-Radical-Military Reconstruction",
        "Andrew Johnson Impeachment",
        "Reconstruction southern state governments",
        "Scalawags",
        "Carpetbaggers",
        "Forty acres and a mule",
        "Dunning School of historical interpretation",
        "Ku Klux Klan",
        "Force Acts (reconstruction)",
        "Mississippi Plan (1875)",
        "White Supremacy terrorism (reconstruction)",
        "Compromise of 1877",
        "Redeemers",
        "Tenant farming",
        "Sharecropping and crop-lien system",
        "Duke tobacco",
        "Southern voting discrimination laws",
        "Jim Crow laws",
        "Slaughterhouse cases, U.S. v Cruikshank and Civil Rights Cases",
        "Plessy vs Ferguson",
        "Ida B. Wells",
        "Exodusters",
        "Lost Cause of the Confederacy",
        "Booker T. Washington",
        "Atlanta Compromise",
        "W.E.B DuBois",
        "Niagara Movement (1905)",
        "National Association for the Advancement of Colored People (NAACP)",
        "Peoples-Societies of the Trans-Mississippi West",
        "Transcontinental railroads",
        "Homestead Act",
        "Mining",
        "Cattle Drives",
        "Cowboy",
        "Open Range",
        "Mark Twain",
        "Buffalo Bill's Wild West Show",
        "Frederick Jackson Turner's frontier thesis",
        "Native American reservation system",
        "Treaty of Fort Laramie (1868)",
        "Indian wars of post-Civil War period",
        "Dawes Severalty Act",
        "Trans-Mississippi West Farming",
        "Andrew Carnegie",
        "John D. Rockefeller",
        "J.P. Morgan",
        "Gustavus Swift and Philip Armour",
        "Duke family",
        "Gospel of Wealth",
        "Social Darwinism",
        "Knights of Labor",
        "American Federation of Labor",
        "Samuel Gompers",
        "Haymarket riot",
        "Homestead strike",
        "Pullman strike",
        "New immigration",
        "Jane Addams",
        "Hull House",
        "Settlement houses",
        "Sherman Antitrust Act",
        "Populism",
        "Panic-Depression of the 1890's",
        "Election of 1896",
        "President William McKinley",
        "Progressivism",
        "Muckrakers",
        "Jacob Riis",
        "Ida Tarbell",
        "Lincoln Steffens",
        "Upton Sinclair",
        "The Jungle",
        "Charlotte Perkins Gilman",
        "Social Gospel",
        "Triangle Shirtwaist Fire",
        "Al Smith",
        "Income tax (16th Amendment)",
        "Direct Election of Senators (17th Amendment)",
        "NAWSA",
        "Carrie Chapman Catt",
        "National Women's Party",
        "Alice Paul",
        "Booker T. Washington",
        "W.E.B. Du Bois",
        "Marcus Garvey",
        "Square Deal",
        "New Freedom",
        "Federal Reserve Act",
        "Clayton Antitrust Act",
        "Acquisition of Alaska",
        "Alfred Thayer Mahan",
        "Spanish American War",
        "Teller Amendment",
        "Platt Amendment",
        "Philippine War",
        "Open Door Policy",
        "Boxer Rebellion",
        "President Theodore Roosevelt",
        "Panama Canal",
        "Roosevelt Corollary",
        "Big Stick Diplomacy",
        "Dollar Diplomacy",
        "Moral Diplomacy",
        "President Woodrow Wilson",
        "Lusitania incident",
        "Sussex Pledge",
        "Fourteen Points",
        "Treaty of Versailles",
        "Ratification fight over the Treaty of Versailles",
        "Great Migration (of the 20th century)",
        "Red Scare",
        "Palmer Raids",
        "Women's suffrage amendment (19th amendment)",
        "Andrew Mellon's trickle-down economics",
        "Henry Ford",
        "Harding Scandals",
        "Lost Generation",
        "Jazz Age",
        "Prohibition (18th amendment)",
        "National Origins Act",
        "Scopes Trial",
        "Harlem Renaissance",
        "Election of 1928",
        "Stock Market Crash",
        "Bonus March",
        "New Deal",
        "President Franklin D. Roosevelt",
        "Hundred Days",
        "National Recovery Administration (NRA)",
        "Agricultural Adjustment Agency (AAA)",
        "Federal Deposit Insurance Corporation (FDIC)",
        "Second New Deal",
        "Social Security Act",
        "Wagner National Labor Relations Act",
        "Works Progress Administration (WPA)",
        "Rural Electrification Administration (REA)",
        "Huey Long",
        "Dr. Francis Townsend",
        "Fr. Charles Coughlin",
        "Congress of Industrial Organization (CIO)",
        "John L. Lewis",
        "Sit-down strikes",
        "Supreme Court Packing Plan",
        "Roosevelt Recession",
        "Conservative coalition",
        "Isolationist Movement",
        "Unilateralism vs. multilateralism",
        "Destroyer for bases agreement (between U.S. and Britain)",
        "Lend Lease",
        "Fair Employment Practices Commission (FEPC)",
        "World War II war production",
        "Rosie the Riveter",
        "Japanese Internment",
        "Yalta Conference",
        "President Harry Truman",
        "Atomic Bomb Controversy",
        "GI Bill",
        "United Nations",
        "Taft-Hartley Act",
        "George Kennan's long telegram",
        "Dean Acheson",
        "Truman Doctrine",
        "Second Red Scare",
        "Federal Employee Loyalty Program (FELP)",
        "George C. Marshall",
        "Marshall Plan",
        "Berlin (Airlift) Crisis",
        "NATO",
        "Truman's civil rights proposals",
        "Shocks of '49",
        "Chinese Revolution",
        "Korean War",
        "Truman vs. MacArthur",
        "McCarthyism",
        "President Dwight Eisenhower",
        "(post-WWII) Conservative movement",
        "Warren Court",
        "Beats",
        "Brown Decision",
        "Montgomery Bus Boycott",
        "Dr. Martin Luther King Jr.",
        "Greensboro Sit-ins",
        "National Highway Act/Interstate Highway Act",
        "CIA: Iran and Guatemala",
        "Containment vs. rollback",
        "Sputnik",
        "Space Race",
        "U-2 Affair",
        "President John F. Kennedy",
        "Bay of Pigs Incident",
        "Creation of Berlin Wall",
        "Cuban Missile Crisis",
        "Birmingham protests",
        "President Lyndon B. Johnson",
        "Civil Rights Act of 1964",
        "Great Society",
        "Michael Harrington's The Other America",
        "War on Poverty",
        "Immigration Act of 1965",
        "Medicare",
        "Students for a Democratic Society",
        "Free Speech Movement",
        "Young Americans for Freedom",
        "Counterculture",
        "Betty Freidan's The Feminine Mystique",
        "Selma protests",
        "Voting Rights Act",
        "Watts Disturbances",
        "Black Power Movement",
        "Gulf of Tonkin controversy",
        "Tet Offensive",
        "1968",
        "Election of 1968",
        "Governor George Wallace",
        "President Richard Nixon",
        "Détente",
        "Cambodia Invasion",
        "Nixon's visit to China",
        "SALT I",
        "Watergate Crisis",
        "1970s cultural divisions",
        "Ralph Nader",
        "Rachel Carson's Silent Spring",
        "Three Mile Island crisis",
        "Human Rights foreign policy",
        "Iranian Hostage Crisis",
        "President Ronald Reagan",
        "Reaganomics",
        "Iran-Contra scandal",
        "INF treaty",
        "Tiananmen Square Controversy",
        "Fall of the Berlin Wall",
        "End of the Cold War",
        "Persian Gulf War (1991)",
        "Clinton's budget plan (1993)",
        "Welfare reform",
        "Bill Clinton's impeachment",
        "Election of 2000",
        "9-11"]

with open('/Users/hshi/Desktop/2023-2024_School_Documents/APUSH/formatted_APUSH_terms.txt', 'w') as file:
    for i in range (len(terms), ):
        file.write(format(terms[len(terms)-1-i], i+1) + "\n")





